---
title: "FPGA Design"
format:
  html: 
    code-links:
      - text: "Code Repository"
        href: https://github.com/chrwu17/MechaCrypt.git
        icon: github
---
## FPGA Design Target

## FPGA Systems

### Bridge Module

The bridge module is responsible for transferring the encryption key generated by MCU 1 (via the TRNG) and the total message length expected from the sender. The key is required by FPGA 2 to decrypt the incoming message, while the length is used for data checking and tracking transfer progress, which will be shown to the user. To support this, FPGA 2 communicates with both MCUs through a custom SPI interface where the FPGA shifts in 128 bits of key and 8 bits of message length from MCU 1 (MSB-first), and later shifts out the same 136-bit block to MCU 2. The protocol follows SPI Mode 0 timing, where data is sampled on the positive edge of SCK during reception and driven on the negative edge during transmission.

The design uses two independent SPI masters, MCU 1 for writing and MCU 2 for reading ensuring clean transfer boundaries. Each MCU controls its own SCK and CS lines, allowing them to initiate transfers without interfering or risking accidental shifts and stale data. The signal flow is as follows:

1. After message parsing is done and the key is available, MCU 1 calculates the message length and pulls `cs_in` `LOW` to trigger a write transaction on FPGA 2.
2. The FPGA 2 shifts in all 136 bits, then asserts `ready`, indicating that all data is available.
3. MCU 2 receives the signal as a GPIO interrupt and pulls `cs_out` `LOW` to begin its read transaction.
4. Once MCU 2 is done, it pulls `cs_out` `HIGH`. The FPGA detects this rising edge and automatically resets all internal registers back to idle (0).
